### ISSUE TITLE
Request Redirection to https://aka.ms/gcguardrails

### ISSUE THREAD

**Issue by ashfenixx** [canada-ca/cloud-guardrails-azure#8]
Requesting to modify "TBD" and Re-direct to the GC Solution Accelerator at

**https://aka.ms/gcguardrails** 

Thank you.

**Comment by ptd-tbs** [comment]
Added the following on the readme: 

Refer to the [Azure Guardrails Solution Accelerator](https://aka.ms/gcguardrails) for more information.
